parameters:
    products_images_directory: '%kernel.project_dir%/public/uploads/products'

services:       
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # explicitly wire JwtService with env var
    App\Service\JwtService:
        arguments:  
            $jwtSecret: '%env(resolve:JWT_SECRET)%'

