parameters:
    products_images_directory: '%kernel.project_dir%/public/uploads/products'

services:       
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    # explicitly wire JwtService with env var
    App\Service\JwtService:
        arguments:  
            $jwtSecret: '%env(resolve:JWT_SECRET)%'
    
    # Register ActivityLogSubscriber as Doctrine event subscriber
    App\EventSubscriber\ActivityLogSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

